### ISSUE TITLE
profile 정렬 문제

### ISSUE THREAD

**Issue by Qlrl** [ripplelover/community-for-KW#3]
profile에서
<img width="596" alt="image" src="https://github.com/ripplelover/community-for-KW/assets/125976282/13f9a39d-6824-47d8-a1b4-42a21fb5b328">
위 사진처럼 가운데 정렬이 되어야 하지만, 
<img width="596" alt="image" src="https://github.com/ripplelover/community-for-KW/assets/125976282/9436ea76-9915-420c-bb55-3d0ab4dd6f83">
이렇게 정렬이 되는 문제가 발생한다.

**Comment by ripplelover** [comment]
정렬 문제 해결완료
<img width="491" alt="image" src="https://github.com/ripplelover/community-for-KW/assets/117145399/d370f684-a73d-417b-8ae4-03d9bfc984e3">
