### ISSUE TITLE
uploaded 수정 필요

### ISSUE THREAD

**Issue by Qlrl** [ripplelover/community-for-KW#7]
<img width="431" alt="image" src="https://github.com/ripplelover/community-for-KW/assets/125976282/204146ca-f690-4d8d-a875-e6fa03bac8b8">

Create Post에서 업로드를 하지 않았는데도, "Uploaded"가 되어있는 문제가 발생함.

**Comment by ripplelover** [comment]
관련 부분 수정 완료 css 부분에서 display를 none으로 해주고 있지 않았음.
![image](https://github.com/ripplelover/community-for-KW/assets/117145399/77941c97-c6c4-4a88-a022-6f2c8ed33ab6)
